### ISSUE TITLE
请问关于datasets文件夹

### ISSUE THREAD

**Issue by ZZZdb** [sunxiaojie99/Relation_Extraction_zh#2]
我在readme_zh中看到datasets文件夹，请问该文件夹里的内容哪里可以获得？

**Comment by sunxiaojie99** [comment]
> 我在readme_zh中看到datasets文件夹，请问该文件夹里的内容哪里可以获得？

这个是我根据在根据中文维基百科的infobox，结合远程监督的方法构造的，可能不是很方便共享。该仓库主要是提供一个基本的关系抽取代码，可供入门～

**Comment by ZZZdb** [comment]
好的，谢谢你的快速回复。
